# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('private', models.BooleanField(default=False)),
                ('password_protected', models.BooleanField(default=False)),
                ('password', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banterbox.Class')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banterbox.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('email', models.TextField(unique=True)),
                ('active', models.BooleanField()),
                ('password', models.TextField()),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserClassEnrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banterbox.Class')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banterbox.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoomRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banterbox.Roles')),
                ('room_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banterbox.Room')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banterbox.User')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='lecturer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banterbox.User'),
        ),
        migrations.AddField(
            model_name='room',
            name='status_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banterbox.Status'),
        ),
        migrations.AddField(
            model_name='comment',
            name='room_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banterbox.Room'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banterbox.User'),
        ),
        migrations.AddField(
            model_name='class',
            name='lecturer_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banterbox.User'),
        ),
    ]
