# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banterbox', '0002_auto_20160830_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
    ]
