# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banterbox', '0003_auto_20160830_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='lecturer_id',
            new_name='lecturer',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='lecturer_id',
            new_name='lecturer',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='class_id',
            new_name='room_class',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='scheduledroom',
            old_name='class_id',
            new_name='room_class',
        ),
        migrations.RenameField(
            model_name='userclassenrolment',
            old_name='class_id',
            new_name='enroled_class',
        ),
        migrations.RenameField(
            model_name='userclassenrolment',
            old_name='user_id',
            new_name='enroled_user',
        ),
        migrations.RenameField(
            model_name='userroomrole',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='userroomrole',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='userroomrole',
            old_name='user_id',
            new_name='user',
        ),
    ]
