# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 05:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banterbox', '0004_auto_20160830_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserUnitEnrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Class',
            new_name='Unit',
        ),
        migrations.DeleteModel(
            name='PasswordReset',
        ),
        migrations.RemoveField(
            model_name='userclassenrolment',
            name='enroled_class',
        ),
        migrations.RemoveField(
            model_name='userclassenrolment',
            name='enroled_user',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_class',
            new_name='room_unit',
        ),
        migrations.RenameField(
            model_name='scheduledroom',
            old_name='room_class',
            new_name='room_unit',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='lecturer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unit',
            name='lecturer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userroomrole',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserClassEnrolment',
        ),
        migrations.AddField(
            model_name='userunitenrolment',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banterbox.Unit'),
        ),
        migrations.AddField(
            model_name='userunitenrolment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
